### ISSUE TITLE
json-provider распознает вложенный массив как стрингу

### ISSUE THREAD

**Issue by AlenaLosk** [sbtqa/datajack#42]
@kosteman, @clicman нужна ваша помощь
Обращение к ключу X-User у Json следующего типа:
`{
  "X-User": {
    "systemId": "QJ160",
    "customerIds": [
      {
        "id": "93V",
        "branch": "Cu19"
      }
    ]
  }
}`
Приводит к возврату такого value:
`{ "systemId" : "QJ160" , "customerIds" : "[ { \"id\" : \"93V\" , \"branch\" : \"Cu19\"}]"}`
Вместо ожидаемого:
`{ "systemId" : "QJ160" , "customerIds" : [ { "id" : "93V" , "branch" : "Cu19"}]}`

**Comment by clicman** [comment]
А что надо чтобы достал?
